---
- name: create k8s users
  hosts: master
  gather_facts: yes
  tasks:
    - name: Loop through hackmaze clusters
      include_tasks: create-user.yml
      vars:
        UserName: "{{ item.username }}"
        GroupName: "{{ item.groupname }}"
        Namespace: "{{ item.namespace }}"
        ClusterName: "{{ item.clustername }}"
        ClusterAddress: "{{ item.clusteraddress }}"
        Role: "{{ item.role }}"
        WID: "{{ item.wid }}"
        WTOKEN: "{{ item.wtoken }}"
      loop:

        - username: "mostafa"
          groupname: "devops"
          namespace: "default"
          clustername: "kubernetes"
          clusteraddress: "{{ hostvars['control']['ansible_default_ipv4']['address'] }}"
          role: "devops"
          sudo: true
          wid: "{{ mostafawid }}"
          wtoken: "{{ mostafawtoken }}"




        - username: "mrym"
          groupname: "backend-dev"
          namespace: "default"
          clustername: "kubernetes"
          clusteraddress: "{{ hostvars['control']['ansible_default_ipv4']['address'] }}"
          role: "developer"
          wid: "{{ mrymwid }}"
          wtoken: "{{ mrymwtoken }}"



        - username: "ziad"
          groupname: "backend-dev"
          namespace: "default"
          clustername: "kubernetes"
          clusteraddress: "{{ hostvars['control']['ansible_default_ipv4']['address'] }}"
          role: "developer"
          wid: "{{ yusufwid }}"
          wtoken: "{{ yusufwtoken }}"


        - username: "moali"
          groupname: "frontend-dev"
          namespace: "default"
          clustername: "kubernetes"
          clusteraddress: "{{ hostvars['control']['ansible_default_ipv4']['address'] }}"
          role: "developer"
          wid: "{{ moaliwid }}"
          wtoken: "{{ moaliwtoken }}"


        - username: "juba"
          groupname: "security"
          namespace: "default"
          clustername: "kubernetes"
          clusteraddress: "{{ hostvars['control']['ansible_default_ipv4']['address'] }}"
          role: "security"
          wid: "{{ jubawid }}"
          wtoken: "{{ jubawtoken }}"


        - username: "norhan"
          groupname: "security"
          namespace: "default"
          clustername: "kubernetes"
          clusteraddress: "{{ hostvars['control']['ansible_default_ipv4']['address'] }}"
          role: "security"
          wid: "{{ nourwid }}"
          wtoken: "{{ nourwtoken }}"

      loop_control:
        loop_var: item
      no_log: true
