---
- name: create k8s users
  hosts: master
  gather_facts: yes
  tasks:
    - name: Loop through hackmaze clusters
      include_tasks: create-user.yml
      vars:
        UserName: "{{ item.username }}"
        GroupName: "{{ item.groupname }}"
        Namespace: "{{ item.namespace }}"
        ClusterName: "{{ item.clustername }}"
        ClusterAddress: "{{ item.clusteraddress }}"
        Role: "{{ item.role }}"
        WID: "{{ item.wid }}"
        WTOKEN: "{{ item.wtoken }}"
      loop:

        - username: "mostafa"
          groupname: "devops"
          namespace: "default"
          clustername: "kubernetes"
          clusteraddress: "{{ hostvars['control']['ansible_default_ipv4']['address'] }}"
          role: "devops"
          wid: "{{ lookup('env', 'mostafawid') }}"
          wtoken: "{{ lookup('env', 'mostafawtoken') }}"




        - username: "mrym"
          groupname: "backend-dev"
          namespace: "default"
          clustername: "kubernetes"
          clusteraddress: "{{ hostvars['control']['ansible_default_ipv4']['address'] }}"
          role: "developer"
          wid: "{{ lookup('env', 'mrymwid') }}"
          wtoken: "{{ lookup('env', 'mrymwtoken') }}"



        - username: "yusuf"
          groupname: "backend-dev"
          namespace: "default"
          clustername: "kubernetes"
          clusteraddress: "{{ hostvars['control']['ansible_default_ipv4']['address'] }}"
          role: "developer"
          wid: "{{ lookup('env', 'yusufwid') }}"
          wtoken: "{{ lookup('env', 'yusufwtoken') }}"


        - username: "moali"
          groupname: "frontend-dev"
          namespace: "default"
          clustername: "kubernetes"
          clusteraddress: "{{ hostvars['control']['ansible_default_ipv4']['address'] }}"
          role: "developer"
          wid: "1205701002939072564"
          wtoken: "Xytqnq_Abu8tncpmXIfqL73371z5ax0AF9zCHoup2MrdW3LouNg5C70cjvOtvyIi5lAe"


        - username: "juba"
          groupname: "security"
          namespace: "default"
          clustername: "kubernetes"
          clusteraddress: "{{ hostvars['control']['ansible_default_ipv4']['address'] }}"
          role: "security"
          wid: "{{ lookup('env', 'jubawid') }}"
          wtoken: "{{ lookup('env', 'jubawtoken') }}"


        - username: "norhan"
          groupname: "security"
          namespace: "default"
          clustername: "kubernetes"
          clusteraddress: "{{ hostvars['control']['ansible_default_ipv4']['address'] }}"
          role: "security"
          wid: "{{ lookup('env', 'nourwid') }}"
          wtoken: "{{ lookup('env', 'nourwtoken') }}"

