---
- name: Loop through hackmaze clusters
 include_tasks: create-user.yml
 vars:
    username: "{{ item.username }}"
    groupname: "{{ item.groupname }}"
    namespace: "{{ item.namespace }}"
    clustername: "{{ item.clustername }}"
    clusteraddress: "{{ item.clusteraddress }}"
    verbs: "{{ item.verbs }}"
    resources: "{{ item.resources }}"
 loop:
    - { username: 'user1', groupname: 'group1', namespace: 'ns1', clustername: 'cluster1', clusteraddress: 'addr1', verbs: 'create,delete', resources: 'pod,deployment' }
    - { username: 'user2', groupname: 'group2', namespace: 'ns2', clustername: 'cluster2', clusteraddress: 'addr2', verbs: 'update,patch', resources: 'daemonset,statefulset' }
