- hosts: master
  become: yes
  tasks:
    - name: clone kubernetes manifests 
      become_user: hackmaze-user
      git:
        repo: 'https://github.com/Hack-Maze/k8s.git'
        dest: $HOME/k8s
        
                
    - name: applying kubernetes manifests 
      become_user: hackmaze-user
      shell: kubectl apply -f .
      args:
        chdir: $HOME/k8s  


    - name: Add Prometheus manifests
      become_user: hackmaze-user
      shell: |
        kubectl create -f promanifests/setup
        until kubectl get servicemonitors --all-namespaces ; do date; sleep 1; echo ""; done
        kubectl create -f promanifests/
      ignore_errors: true
      args:
        chdir: $HOME/k8s


    - name: applying kubernetes cert manifests 
      become_user: hackmaze-user
      shell: kubectl apply -f cert/
      args:
        chdir: $HOME/k8s  
