- hosts: master
  become: yes
  tasks:
    - name: create an empty file for Kubeadm configuring
      become: yes
      copy:
        content: ""
        dest: /etc/kubernetes/kubeadm-config.yaml
        force: yes

    - name: configuring the container runtime including its cgroup driver
      blockinfile:
        path: /etc/kubernetes/kubeadm-config.yaml
        block: |
              kind: ClusterConfiguration
              apiVersion: kubeadm.k8s.io/v1beta3
              networking:
                podSubnet: "10.244.0.0/16"
              ---
              kind: KubeletConfiguration
              apiVersion: kubelet.config.k8s.io/v1beta1
              runtimeRequestTimeout: "15m"
              cgroupDriver: "systemd"
              systemReserved:
                cpu: 100m
                memory: 350M
              kubeReserved:
                cpu: 100m
                memory: 50M
              enforceNodeAllocatable:
              - pods

    - name: initialize the cluster (this could take some time)
      become: yes
      shell: kubeadm init --config /etc/kubernetes/kubeadm-config.yaml  --ignore-preflight-errors=NumCPU,Mem >> cluster_initialized.log 
      args:
        chdir: /home/hackmaze-user
        creates: cluster_initialized.log

    - name: create .kube directory
      become: yes
      become_user: hackmaze-user
      file:
        path: $HOME/.kube
        state: directory
        mode: 0755

    - name: copy admin.conf to user's kube config
      become: yes
      copy:
        src: /etc/kubernetes/admin.conf
        dest: /home/hackmaze-user/.kube/config
        remote_src: yes
        owner: hackmaze-user

    - name: install Pod network
      become: yes
      become_user: hackmaze-user
      shell: kubectl apply -f https://raw.githubusercontent.com/flannel-io/flannel/master/Documentation/kube-flannel.yml >> pod_network_setup.log
      args:
        chdir: $HOME
        creates: pod_network_setup.log

    - name: clone kubernetes manifests 
      become_user: hackmaze-user
      git:
        repo: 'https://github.com/Hack-Maze/k8s'
        dest: $HOME

    - name: applying kubernetes manifests 
      become_user: hackmaze-user
      shell: kubectl apply -f .
      args:
        chdir: $HOME/k8s       